
substitutions:
  _LOCATION: us-central1
  _AR_REPO: docker-artifact-registry
  _IMAGE_NAME: cscratch

steps:
# Build and push with Kaniko to Artifact Registry
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest
  - --cache=true
  - --cache-ttl=24h

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_IMAGE_NAME}'
  - '--image'
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}'
  - '--region'
  - '${_LOCATION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY
