steps:
# --- 1. RUN UNIT TESTS ---
# We use a standard python container to run tests before packaging.
# If this fails, the build stops and we don't deploy broken code.
- name: 'python:3.11-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install -r requirements.txt &&
    pytest tests/

# --- 2. BUILD CONTAINER ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cscratch', '.']

# --- 3. PUSH CONTAINER ---
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cscratch']

# --- 4. DEPLOY TO CLOUD RUN ---
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'cscratch'
  - '--image'
  - 'gcr.io/$PROJECT_ID/cscratch'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--min-instances=0'
  - '--max-instances=1'
  - '--set-secrets'
  - 'INTERNAL_API_KEY=cscratch-internal-api-key:latest,DISCORD_TOKEN=cscratch-discord-token:latest'

images:
- 'gcr.io/$PROJECT_ID/cscratch'

options:
  logging: CLOUD_LOGGING_ONLY